extends: default

rules:
  line-length:
    max: 120
    level: warning

  document-start: disable

  indentation:
    spaces: 2
    indent-sequences: false

  truthy:
    allowed-values: ["true", "false", "on", "off"]

  comments:
    min-spaces-from-content: 1
